### PR TITLE
Fix Travis Configuration

### PR DESCRIPTION
**Pull request by madoar**
The travis configuration seems to be out of date

### CODE REVIEW

**Comment by madoar** [comment]
I fear that the gradle build is very outdated

**Comment by madoar** [comment]
I've dropped Java 8 from the test matrix because it is quite difficult to include because of the different approach to include JavaFX. 

The tests should be running now on travis. We just need to wait for OSX to finish.

The linux tests show that two tests are failing @neutronc

**Comment by neutronc** [comment]
Locally those tests succeeded on my machine :(

**Comment by madoar** [comment]
> UTF Problem from surefire ? have a look at the POM.XML surefire argline dont know if thats working on travis...

I don't think this is the reason, I also face two failing tests on my PC:

```
...
2020-03-16 22:36:10 ERROR Game load failed 
java.lang.IllegalStateException: Currently only a single instance of RailsRoot is allowed
        at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
        at net.sf.rails.game.RailsRoot.create(RailsRoot.java:78)
        at net.sf.rails.util.GameLoader.createFromFile(GameLoader.java:315)
        at net.sf.rails.test.TestGame.setUp(TestGame.java:102)
        at junit.framework.TestCase.runBare(TestCase.java:140)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:130)
        at junit.framework.TestSuite.runTest(TestSuite.java:241)
        at junit.framework.TestSuite.run(TestSuite.java:236)
        at junit.framework.TestSuite.runTest(TestSuite.java:241)
        at junit.framework.TestSuite.run(TestSuite.java:236)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Could not create test fail report
[ERROR] Tests run: 28, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 5.285 s <<< FAILURE! - in net.sf.rails.test.TestGameBuilder
[ERROR] test/1837_TileLayingCheck-Privates(net.sf.rails.test.TestGame)  Time elapsed: 0.147 s  <<< ERROR!
java.lang.NullPointerException
        at net.sf.rails.test.TestGame.setUp(TestGame.java:102)

[ERROR] test/1851_Late(net.sf.rails.test.TestGame)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.NullPointerException
        at net.sf.rails.test.TestGame.gameReportTest(TestGame.java:60)
        at net.sf.rails.test.TestGame.runTest(TestGame.java:41)

...
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   TestGame.setUp:102 » NullPointer
[ERROR]   TestGame.runTest:41->gameReportTest:60 NullPointer
[INFO] 
[ERROR] Tests run: 169, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by neutronc** [comment]
Interesting...

**Comment by madoar** [comment]
Running `mvn clean test` also creates two "new" (unversioned) files:

```
        src/test/resources/data/real/1830_B.report
        src/test/resources/data/test/1837_StartroundCompleted.report
```

**Comment by madoar** [comment]
Slightly off-topic:
Does the gradle configuration work for you or are you building and testing the application with maven?
If it does not work for you do you think we can remove the gradle configuration?

**Comment by neutronc** [comment]
OK in my build (maven) teh test for the NAtDoubleShare now fails.. But that might have to do something with my recent changes..

The 1851.Late is working though,

I'll version the two new tests..

**Comment by madoar** [comment]
The tests fail on macOS as well. Tell me if I should rebase this PR.

**Comment by neutronc** [comment]
No i think you should move ahead with the fixes.
I'll fixthe test games this week didnt have the time today.

**Comment by madoar** [comment]
@neutronc which OS do you use to run the tests?

**Comment by madoar** [comment]
Now only a single test is failing:

```
...
2020-03-18 20:43:29 INFO  Loading game from file /home/travis/build/Rails-18xx/Rails/src/test/resources/data/test/1835_NatDoubleShare.rails 
2020-03-18 20:43:29 INFO  Reading Rails 1.5.3+ 2009-11-06 saved file 1835_NatDoubleShare.rails 
2020-03-18 20:43:29 INFO  File was saved at 2011-11-21 17:26:22 
2020-03-18 20:43:29 INFO  ========== Start of rails.game 1835 ========== 
2020-03-18 20:43:29 INFO  Rails version 2.0.RC5.9 
2020-03-18 20:43:29 INFO  Phase=1 ORs=IntegerState{uri=/GameManager/numOfORs} 
2020-03-18 20:43:29 INFO  Initial operating sequence is M1,M2,M3,M4,M5,M6,BY 
2020-03-18 20:43:29 INFO  Phase=1 ORs=IntegerState{uri=/GameManager/numOfORs} 
2020-03-18 20:43:29 INFO  Initial operating sequence is M1,M2,M3,M4,M5,M6,BY 
2020-03-18 20:43:29 INFO  Phase=1 ORs=IntegerState{uri=/GameManager/numOfORs} 
2020-03-18 20:43:29 INFO  Initial operating sequence is M1,M2,M3,M4,M5,M6,SX,BY 
2020-03-18 20:43:29 INFO  Phase=1 ORs=IntegerState{uri=/GameManager/numOfORs} 
2020-03-18 20:43:29 INFO  Initial operating sequence is M1,M2,M3,M4,M5,M6,BY,SX 
2020-03-18 20:43:29 INFO  Phase=1 ORs=IntegerState{uri=/GameManager/numOfORs} 
2020-03-18 20:43:29 INFO  Initial operating sequence is M1,M2,M3,M4,M5,M6,BY,SX,BA 
2020-03-18 20:43:29 INFO  Phase=2 ORs=IntegerState{uri=/GameManager/numOfORs} 
2020-03-18 20:43:29 INFO  Initial operating sequence is M1,M2,M3,M4,M5,M6,BY,SX,WT,BA 
2020-03-18 20:43:29 INFO  Initial operating sequence is M1,M2,M3,M4,M5,M6,BY,SX,BA,WT 
2020-03-18 20:43:29 WARN  Replay of game interrupted 
2020-03-18 20:43:29 ERROR Game load failed 
net.sf.rails.util.RailsReplayException: LoadInterrupted,332
	at net.sf.rails.util.GameLoader.replayGame(GameLoader.java:271)
	at net.sf.rails.util.GameLoader.createFromFile(GameLoader.java:330)
	at net.sf.rails.test.TestGame.setUp(TestGame.java:102)
	at junit.framework.TestCase.runBare(TestCase.java:140)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Could not create test fail report
...
[ERROR] Tests run: 26, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.154 s <<< FAILURE! - in net.sf.rails.test.TestGameBuilder
[ERROR] test/1835_NatDoubleShare(net.sf.rails.test.TestGame)  Time elapsed: 0.235 s  <<< ERROR!
java.lang.NullPointerException
	at net.sf.rails.test.TestGame.gameReportTest(TestGame.java:60)
	at net.sf.rails.test.TestGame.runTest(TestGame.java:41)
...
```

**Comment by neutronc** [comment]
> 
> 
> @neutronc which OS do you use to run the tests?

Windows

**Comment by neutronc** [comment]
Can you run the checks again ? with the new testgame they might pass.

**Comment by madoar** [comment]
They already did rerun using Github Actions, they are working :)

**Pull request closed without merging**
