### PR TITLE
initial pass at Slack

### PR DESCRIPTION
**Pull request by jklap**
Slack notification support similar to Discord notification support.

Added Slack webhook and user name mapping configurations to existing Notification config pane with the Discord configurations

### CODE REVIEW

**Comment by jklap** [comment]
Something like a Config.infoText kind of thing or documentation elsewhere?

**Comment by neutronc** [comment]
I honestly think we need both :)

**Comment by jklap** [comment]
I'll add the Config.infoText.

Where should the "elsewhere" be?

**Comment by neutronc** [comment]
Hm thinking out loud, it really belong into our Wiki imho.
Otherwise we would have to have a stack of docs being created and delivered.

But maybe we can discuss that in our slack channel for more input from other people ?

**Pull request merged**
