### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by madoar**
- execute the tests on JDK 8
- execute the tests on JDK 11

### CODE REVIEW

**Comment by madoar** [comment]
@neutronc this PR makes use of Github Actions instead of Travis to run the tests and build the `jar` archive. The benefit here is that we can run the tests on all three most popular operating systems and with both JDK 8 and 11. What do you think about this (especially compared to Travis)?

**Comment by neutronc** [comment]
Hi what ever helps us with automatic testing is good :)

Btw i think i am a bit nearer to the error with the game that fails in tests.
On Windows it works as a charm on linux it bails in the JavaFX section of trying to build a Configuration ? So what ever is the error is treated in JavaFX differently on Linux than on Windows.

**Comment by madoar** [comment]
Why do you think the issue is in the JavaFX code?

**Comment by neutronc** [comment]
Cause it bailed on my Ubuntu system in the ConfigWindow.java ? 
Check it out by loading the 1851 test game ?

**Comment by madoar** [comment]
But the failing test is for an 1835 test case?

**Comment by neutronc** [comment]
grafik

On my windows system they all run with the current base without any issues..

**Comment by madoar** [comment]
Maybe it is really something about the game files that are different on windows compared to other systems

**Comment by madoar** [comment]
Ok maybe I can help you somehow. I debugged the test case a bit. 

Let's start at the end. The test fails at:

https://github.com/Rails-18xx/Rails/blob/841adc14a974d2afea52d252e417a205851c103b/src/main/java/net/sf/rails/util/GameLoader.java#L271

This occurs because previously `GameManager#processOnReload` returns `false` in:

https://github.com/Rails-18xx/Rails/blob/841adc14a974d2afea52d252e417a205851c103b/src/main/java/net/sf/rails/game/GameManager.java#L880-L884

This again is the case because `possibleActions#validate` returns `false` in:

https://github.com/Rails-18xx/Rails/blob/841adc14a974d2afea52d252e417a205851c103b/src/main/java/rails/game/action/PossibleActions.java#L86-L102

The internal state of the method/object when it returns `false in` line 101 is as followed:

grafik

If you need additional information feel free to ask :)

**Pull request merged**
