### PR TITLE
learn how to store the log file in a user specified location and defa…

### PR DESCRIPTION
**Pull request by jklap**
…ulting to home

This PR adds:
* The ability to customize the log directory and log file name via user configuration (which existed before but didn't actually seem to be used anywhere/actually work!)
* Supports templating of the log file name configuration allowing things such '${date:yyyy-MM-dd}' to inject a date into the file name
* Changes the default to using '~/.rails/` on Mac & Linux and '~/Rails/' on Windows
* Changes the default file name to include `HHmmss` to avoid clashing with running multiple Rails instances at the same time
* Sanitizes the file name for Linux and Mac replacing ` ` with `_` to avoid the dreaded spaces-in-file-names issue on those platforms

### CODE REVIEW

**Comment by jklap** [comment]
@neutronc @madoar  can you both please test this on your respective platforms, especially the default (no configuration) setting?

**Comment by madoar** [comment]
grafik

Shouldn't there be a default `Log filename pattern` and `Log directory`? Is it because of an old configuration which is saved somewhere?

**Comment by jklap** [comment]
No-- this is only for *overriding* the built-in application level default.

**Comment by madoar** [comment]
Yeah but why isn't the built in default setting shown in the UI?

My point is not to say that this is an issue with this PR. I just want to know if:
- this is intended?
- if it is not intended where it should be fixed? (as part of this PR or in a separate PR)

**Comment by jklap** [comment]
Yes, this is intended. This is not to define what/where the logs should be written, this is simply to allow the user to override the defaults to that of their choosing. Same behavior similar to the save directory-- not set, has a sensible default

**Comment by madoar** [comment]
Just to be sure that I test this PR correctly, here some some questions about how I should test this:

You want me to:
-  test this PR once without any configuration set? (i.e. use default settings)
   Question: do you know in which folder the configuration is saved in case I need to delete it?
-  test this PR once with changed a logging configuration (log directory + log filename)
   Questions: 
      - this should be set under `Configuration -> Log`, right?
      - do you have any specific log directories or log filenames I should test?

**Comment by jklap** [comment]
Thinking:
* Test with the default settings-- which on Mac & Linux should write to ~/.rails/18xx.log
* Test with a specified folder and maybe the date format I included in the PR description

Not too worried about either given Mac and Linux are pretty similar in regards to file systems but just want to make sure the first is correct on Linux (as the second I'm pretty comfortable with).

For the profile details I'm not sure but should be listed to stdout if you start the jar from the command line:
```
04-15-2020:23:37:55.110 [main] INFO  n.s.r.u.Util->invoke0():-2 - Loading properties from file /Users/jklap/Library/Preferences/net.sourceforge.rails/rails.recent
04-15-2020:23:37:55.111 [main] INFO  n.s.r.u.Util->invoke0():-2 - Loading properties from resource data/profiles/LIST_OF_PROFILES
04-15-2020:23:37:55.111 [main] INFO  n.s.r.u.Util->invoke0():-2 - Loading properties from resource data/profiles/root
04-15-2020:23:37:55.112 [main] INFO  n.s.r.u.Util->invoke0():-2 - Loading properties from file /Users/jklap/Library/Preferences/net.sourceforge.rails/profiles/JK.rails_profile
04-15-2020:23:37:55.112 [main] INFO  n.s.r.u.Util->invoke0():-2 - Loading properties from resource data/profiles/pbem.predefined
04-15-2020:23:37:55.112 [main] INFO  n.s.r.u.Util->invoke0():-2 - Loading properties from resource git.properties
```

For me it's the 4th line above. This is the file you could edit manually for the config settings

**Comment by neutronc** [comment]
ON windows it points on Default to ~user.home/Documents i would have it point to ~user.home/Documents/Rails 
or ~user.home/Appdata/local/Rails...
Otherwise this seems fine.

**Comment by jklap** [comment]
@neutronc if you could please test this change-- should be the user's default Documents directory

**Comment by neutronc** [comment]
> 
> 
> @neutronc if you could please test this change-- should be the user's default Documents directory

I did see comment above

**Comment by jklap** [comment]
Oh sorry-- missed the `Rails/`. Adding now

**Comment by jklap** [comment]
Not sure why the Mac OS dmg creation failed, looks to be something GitHub action related:
```
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jdk.incubator.jpackage9879911915235168924/config/Rails-18xx-dmg-setup.scpt:64:113: execution error: Finder got an error: AppleEvent timed out. (-1712)
```

Builds fine locally

**Pull request merged**
