### PR TITLE
18Scan completed. 

### PR DESCRIPTION
**Pull request by erik-vos**
Status set to Fully Playable.

This PR adds correct calculation of bonus amounts.
In addition there are some minor corrections.

### CODE REVIEW

**Comment by erik-vos** [comment]
It seems that these commits have not made it into upstream/master. When I compare that with my master, these commits are missing. Has anything gone wrong here? 
See also issue #290

**Comment by neutronc** [comment]
the commits are in Rails-18xx:master

**Comment by neutronc** [comment]
did you pull the new master from the origin ?

**Comment by erik-vos** [comment]
No, I pull updates from upstream and push to origin.
Strange. When I compared my local master with upstream/master, the report was that these three commits are missing in upstream/master.
But now I have pulled all new stuff from upstream, and the differences have disappeared. Don't understand, but I rest my case.

**Pull request merged**
